//
// Created by ekblay on 12/1/21.
//


#ifndef REFACTORED_PUZZLES_CONFIG_H
#define REFACTORED_PUZZLES_CONFIG_H

#endif //REFACTORED_PUZZLES_CONFIG_H

int MAX_ITERATIONS =  10000;
int MIN_ITERATIONS = 5000;
int PUZZLE_STRENGTH = 16;